version: '3.8'

services:
  tests:
    build: .
    volumes:
      - ./allure-results:/app/allure-results
      - ./test_logs:/app/test_logs
      - ./screenshots:/app/screenshots
      - ./files:/app/files
    environment:
      - LOGGER_LEVEL=INFO
      # При необходимости можно передать другие переменные
    command: pytest -v --browser=chromium --headless=True --alluredir=allure-results

  allure:
    image: frankescobar/allure-docker-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/allure-reports