version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.16
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.16
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.16
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  tests:
    build: .
    depends_on:
      - selenium-hub
      - chrome
      - firefox
    volumes:
      - ./allure-results:/app/allure-results
      - ./test_logs:/app/test_logs
      - ./screenshots:/app/screenshots
      - ./files:/app/files
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
      - DOWNLOAD_DIR=/app/downloads
    command: pytest -v --browser=chrome --remote-url=http://selenium-hub:4444/wd/hub --alluredir=allure-results


  edge:
    image: selenium/node-edge:4.16
    shm_size: 2gb
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443


# Если не установлен  Allure
  allure:
    image: frankescobar/allure-docker-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
    - "5050:5050"
    volumes:
    - ./allure-results:/app/allure-results
    - ./allure-reports:/app/allure-reports

# Отчет доступен http://localhost:5050
