[pytest]
minversion = 7.0
pythonpath = .
addopts =
    -v
    --strict-markers
    --tb=short
    --alluredir=allure-results
    --browser=chromium
    # --headed           # раскомментируйте, если нужен видимый браузер

markers =
    smoke: Дымовые тесты
    regression: Полный регресс
    api: Тесты API
    ui: Тесты пользовательского интерфейса
    slow: Медленные тесты

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S