import enum


class URLS(enum.StrEnum):
    BASE = "https://opensource-demo.orangehrmlive.com/web/index.php/"
    LOGIN = BASE + "auth/login"
    PASSWORD = BASE + "auth/requestPasswordResetCode"
    DASHBOARD = BASE + "dashboard/index"
    ADMIN = BASE + "admin/viewSystemUsers"
    ADMIN_SAVE = BASE + "admin/saveSystemUser"
    MODULES = BASE + "admin/viewModules"
    LOCALIZATION = BASE + "admin/localization"
    CORP_BRANDING = BASE + "admin/addTheme"
    JOB_TITLE = BASE + "admin/viewJobTitleList"
    ADD_JOB_TITLE = BASE + "admin/saveJobTitle"
    PAY_GRADES = BASE + "admin/viewPayGrades"
    ADD_PAY_GRADES = BASE + "admin/payGrade"
    PIM = BASE + "pim/viewEmployeeList"
    LEAVE = BASE + "leave/viewLeaveList"
    ASSIGN_LEAVE = BASE + "leave/assignLeave"
    APPLY_LEAVE = BASE + "leave/applyLeave"
    MY_LEAVE = BASE + "leave/viewMyLeaveList"
    TIME = BASE + "time/viewEmployeeTimesheet"
    MY_TIME = BASE + "time/viewMyTimesheet"
    ATTENDANCE_PUNCH = BASE + "attendance/punchIn"
    RECRUITMENT = BASE + "recruitment/viewCandidates"
    RECRUITMENT_DASH = BASE + "recruitment/viewCandidates?statusId=4"
    RECRUITMENT_ADD = BASE + "recruitment/addCandidate"
    MYINFO = BASE + "pim/viewPersonalDetails/empNumber/7"
    PERFORMANCE = BASE + "performance/searchEvaluatePerformanceReview"
    PERFORMANCE_DASH = BASE + "performance/myPerformanceReview"
    DIRECTORY = BASE + "directory/viewDirectory"
    MAINTENANCE = BASE + "maintenance/purgeEmployee"
    CLAIM = BASE + "claim/viewAssignClaim"
    BUZZ = BASE + "buzz/viewBuzz"
    RESET = BASE + "auth/requestPasswordResetCode"
